"""add_system_table

Revision ID: 0dc3cdf49683
Revises: 86cf3fe450b4
Create Date: 2026-01-13 12:07:55.342171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc3cdf49683'
down_revision: Union[str, Sequence[str], None] = '86cf3fe450b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('open_nutrition_data_import_started', sa.Boolean(), nullable=False),
    sa.Column('open_nutrition_data_import_finished', sa.Boolean(), nullable=False),
    sa.Column('exercise_import_started', sa.Boolean(), nullable=False),
    sa.Column('exercise_import_finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    # ### end Alembic commands ###
