"""updated_activities

Revision ID: 1dbf2d55ecff
Revises: 0dc3cdf49683
Create Date: 2026-01-13 13:19:45.706803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbf2d55ecff'
down_revision: Union[str, Sequence[str], None] = '0dc3cdf49683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_date'), table_name='activities')
    op.drop_constraint(op.f('activities_goals_id_fkey'), 'activities', type_='foreignkey')
    op.drop_column('activities', 'goals_id')
    op.drop_column('activities', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('goals_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('activities_goals_id_fkey'), 'activities', 'goals', ['goals_id'], ['id'])
    op.create_index(op.f('ix_activities_date'), 'activities', ['date'], unique=False)
    # ### end Alembic commands ###
