"""added indexes 2

Revision ID: 4025fb0e40b6
Revises: 3261310234e8
Create Date: 2026-01-30 15:36:43.286494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4025fb0e40b6'
down_revision: Union[str, Sequence[str], None] = '3261310234e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_food_entries_food_id'), 'food_entries', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_entries_log_id'), 'food_entries', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_entries_log_id'), table_name='food_entries')
    op.drop_index(op.f('ix_food_entries_food_id'), table_name='food_entries')
    # ### end Alembic commands ###
