"""added 'hidden' flag to food_item

Revision ID: 5e2435573fa3
Revises: 284f62bd0c39
Create Date: 2026-01-23 16:31:16.665710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2435573fa3'
down_revision: Union[str, Sequence[str], None] = '284f62bd0c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('hidden', sa.Boolean(), nullable=True))
    # Update existing rows to set hidden=False
    op.execute("UPDATE food_items SET hidden = FALSE WHERE hidden IS NULL")
    # Then make the column non-nullable
    op.alter_column('food_items', 'hidden', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'hidden')
    # ### end Alembic commands ###
