"""added private flag to activity model

Revision ID: 7c4f4d1b1708
Revises: c10cf8198f7c
Create Date: 2026-03-11 20:53:41.402510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f4d1b1708'
down_revision: Union[str, Sequence[str], None] = 'c10cf8198f7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable first
    op.add_column('activities', sa.Column(
        'private', sa.Boolean(), nullable=True))
    # Update existing rows to False
    op.execute("UPDATE activities SET private = FALSE WHERE private IS NULL")
    # Make the column non-nullable
    op.alter_column('activities', 'private', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'private')
    # ### end Alembic commands ###
