"""added onboarding_finished flag for users

Revision ID: 9f67c56e3f10
Revises: 7c4f4d1b1708
Create Date: 2026-03-14 11:40:02.418474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f67c56e3f10'
down_revision: Union[str, Sequence[str], None] = '7c4f4d1b1708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_finished', sa.Boolean(), nullable=True))
    # Update existing rows to set onboarding_finished=False
    op.execute("UPDATE users SET onboarding_finished = FALSE WHERE onboarding_finished IS NULL")
    # Then make the column non-nullable
    op.alter_column('users', 'onboarding_finished', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_finished')
    # ### end Alembic commands ###
