"""added img_name to FoodItem

Revision ID: c10cf8198f7c
Revises: 4025fb0e40b6
Create Date: 2026-01-31 12:15:41.836625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10cf8198f7c'
down_revision: Union[str, Sequence[str], None] = '4025fb0e40b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('img_name', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_items', 'img_name')
    # ### end Alembic commands ###
