<script setup lang="ts">
import { computed, type PropType } from 'vue'
import { VueUiXy, type VueUiXyDatasetItem, type VueUiXyConfig } from 'vue-data-ui'
import 'vue-data-ui/style.css' // If you are using multiple components, place this style import in your main

const config = computed(() => {
  return <VueUiXyConfig>{
    debug: false,
    theme: '',
    responsive: false,
    loading: false,
    events: {
      datapointEnter: null,
      datapointLeave: null,
      datapointClick: null,
    },
    responsiveProportionalSizing: true,
    customPalette: [],
    useCssAnimation: false,
    downsample: {
      threshold: 1500,
    },
    chart: {
      fontFamily: 'inherit',
      backgroundColor: '#FFFFFFff',
      color: '#1A1A1Aff',
      height: 600,
      width: 1000,
      annotations: [
        {
          show: false,
          yAxis: {
            yTop: null,
            yBottom: null,
            label: {
              text: '',
              textAnchor: 'start',
              position: 'start',
              offsetX: 0,
              offsetY: 0,
              padding: {
                top: 12,
                right: 12,
                bottom: 12,
                left: 12,
              },
              border: {
                stroke: '#FFFFFF',
                strokeWidth: 1,
                rx: 0,
                ry: 0,
              },
              fontSize: 14,
              color: '#2D353C',
              backgroundColor: '#e1e5e8',
            },
            line: {
              stroke: '#2D353C',
              strokeWidth: 1,
              strokeDasharray: 0,
            },
            area: {
              fill: '#e1e5e8',
              opacity: 30,
            },
          },
        },
      ],
      zoom: {
        show: true,
        color: '#CCCCCCff',
        highlightColor: '#ffe7a3',
        fontSize: 14,
        useResetSlot: false,
        startIndex: null,
        endIndex: null,
        enableRangeHandles: true,
        enableSelectionDrag: true,
        focusOnDrag: false,
        focusRangeRatio: 0.2,
        minimap: {
          show: true,
          selectedColor: '#ffe7a3',
          selectedColorOpacity: 0.2,
          indicatorColor: '#1A1A1A',
          verticalHandles: false,
          compact: true,
          frameColor: '#ffe7a3',
          smooth: true,
          lineColor: '#1A1A1A',
          selectionRadius: 2,
          merged: true,
        },
        preview: {
          enable: true,
          fill: '#CCCCCC50',
          stroke: '#6A6A6Aff',
          strokeWidth: 2,
          strokeDasharray: 0,
        },
        useDefaultFormat: true,
        timeFormat: 'yyyy-MM-dd HH:mm:ss',
        customFormat: null,
      },
      padding: {
        top: 12,
        right: 12,
        bottom: 5,
        left: 6,
      },
      highlighter: {
        color: '#1A1A1Aff',
        opacity: 5,
        useLine: true,
        lineDasharray: 2,
        lineWidth: 1,
      },
      highlightArea: {
        show: false,
        from: 0,
        to: 0,
        color: '#CCCCCCff',
        opacity: 20,
        caption: {
          text: 'Caption',
          fontSize: 20,
          color: '#1A1A1Aff',
          bold: false,
          offsetY: 0,
          width: 'auto',
          padding: 3,
          textAlign: 'center',
        },
      },
      timeTag: {
        show: false,
        backgroundColor: '#e1e5e8ff',
        color: '#1A1A1Aff',
        fontSize: 12,
        circleMarker: {
          radius: 3,
          color: '#1A1A1Aff',
        },
        useDefaultFormat: true,
        timeFormat: 'yyyy-MM-dd HH:mm:ss',
        customFormat: null,
      },
      grid: {
        stroke: '#e1e5e8ff',
        showVerticalLines: false,
        showHorizontalLines: true,
        position: 'middle',
        frame: {
          show: false,
          stroke: '#E1E5E8ff',
          strokeWidth: 2,
          strokeLinecap: 'round',
          strokeLinejoin: 'round',
          strokeDasharray: 0,
        },
        labels: {
          show: true,
          color: '#1A1A1Aff',
          fontSize: 16,
          axis: {
            yLabel: 'Weight in kg',
            yLabelOffsetX: 0,
            xLabel: '',
            xLabelOffsetY: 0,
            fontSize: 18,
          },
          zeroLine: {
            show: true,
          },
          xAxis: {
            showBaseline: true,
            showCrosshairs: true,
            crosshairsAlwaysAtZero: false,
            crosshairSize: 6,
          },
          yAxis: {
            position: 'left',
            showBaseline: true,
            showCrosshairs: true,
            crosshairSize: 6,
            commonScaleSteps: 10,
            useIndividualScale: false,
            useNiceScale: true,
            stacked: false,
            gap: 12,
            labelWidth: 40,
            formatter: null,
            scaleMin: props.yMin,
            scaleMax: null,
            groupColor: '#1A1A1A',
            scaleLabelOffsetX: 0,
            scaleValueOffsetX: 0,
            rounding: 1,
            serieNameFormatter: null,
          },
          xAxisLabels: {
            color: '#1A1A1Aff',
            show: true,
            values: props.xAxisValues,
            datetimeFormatter: {
              enable: false,
              locale: 'en',
              useUTC: false,
              januaryAsYear: false,
              options: {
                year: 'yyyy',
                month: "MMM 'yy",
                day: 'dd MMM',
                hour: 'HH:mm',
                minute: 'HH:mm:ss',
                second: 'HH:mm:ss',
              },
            },
            fontSize: 18,
            showOnlyFirstAndLast: props.minimalLabels,
            showOnlyAtModulo: false,
            modulo: 12,
            yOffset: 8,
            rotation: 0,
            autoRotate: {
              enable: true,
              angle: -40,
            },
          },
        },
      },
      comments: {
        show: true,
        showInTooltip: true,
        width: 200,
        offsetX: 0,
        offsetY: 0,
      },
      labels: {
        fontSize: 16,
        prefix: '',
        suffix: '',
      },
      legend: {
        color: '#1A1A1Aff',
        show: false,
        fontSize: 16,
        position: 'bottom',
        selectAllToggle: {
          show: false,
          backgroundColor: '#E1E5E8ff',
          color: '#1A1A1Aff',
        },
      },
      title: {
        text: 'Title',
        color: '#1A1A1Aff',
        fontSize: 20,
        bold: true,
        textAlign: 'center',
        paddingLeft: 0,
        paddingRight: 0,
        subtitle: {
          color: '#CCCCCCff',
          text: '',
          fontSize: 16,
          bold: false,
        },
        show: false,
      },
      tooltip: {
        show: true,
        color: '#1A1A1Aff',
        backgroundColor: '#FFFFFFff',
        fontSize: 14,
        customFormat: null,
        borderRadius: 4,
        borderColor: '#e1e5e8',
        borderWidth: 1,
        backgroundOpacity: 30,
        position: 'center',
        offsetY: 24,
        smooth: true,
        backdropFilter: true,
        smoothForce: 0.18,
        smoothSnapThreshold: 0.25,
        teleportTo: 'body',
        showTimeLabel: true,
        showValue: true,
        showPercentage: false,
        roundingValue: 1,
        roundingPercentage: 0,
        useDefaultTimeFormat: true,
        timeFormat: 'yyyy-MM-dd HH:mm:ss',
      },
      userOptions: {
        show: false,
        showOnChartHover: false,
        keepStateOnChartLeave: true,
        position: 'right',
        buttons: {
          tooltip: true,
          pdf: true,
          csv: true,
          img: true,
          table: true,
          labels: true,
          fullscreen: true,
          sort: false,
          stack: true,
          animation: false,
          annotator: true,
          svg: true,
          zoom: false,
        },
        callbacks: {
          animation: null,
          annotator: null,
          csv: null,
          fullscreen: null,
          img: null,
          labels: null,
          pdf: null,
          sort: null,
          stack: null,
          table: null,
          tooltip: null,
          svg: null,
          zoom: null,
        },
        buttonTitles: {
          open: 'Open options',
          close: 'Close options',
          tooltip: 'Toggle tooltip',
          pdf: 'Download PDF',
          csv: 'Download CSV',
          img: 'Download PNG',
          table: 'Toggle table',
          labels: 'Toggle labels',
          fullscreen: 'Toggle fullscreen',
          stack: 'Toggle stack mode',
          annotator: 'Toggle annotator',
          svg: 'Download SVG',
        },
        print: {
          scale: 2,
          orientation: 'auto',
          overflowTolerance: 0.2,
        },
      },
    },
    bar: {
      showTransition: true,
      transitionDurationMs: 300,
      borderRadius: 2,
      useGradient: true,
      periodGap: 0.1,
      innerGap: 0,
      border: {
        useSerieColor: false,
        strokeWidth: 1,
        stroke: '#FFFFFFff',
      },
      labels: {
        show: true,
        offsetY: -8,
        rounding: 0,
        color: '#1A1A1Aff',
        formatter: null,
      },
      serieName: {
        show: false,
        offsetY: -6,
        useAbbreviation: true,
        abbreviationSize: 3,
        useSerieColor: true,
        color: '#1A1A1Aff',
        bold: false,
      },
    },
    line: {
      showTransition: true,
      transitionDurationMs: 300,
      radius: 6,
      useGradient: false,
      strokeWidth: 2,
      cutNullValues: false,
      interLine: {
        pairs: [],
        colors: [],
        fillOpacity: 0.25,
      },
      dot: {
        hideAboveMaxSerieLength: 62,
        useSerieColor: false,
        fill: '#FFFFFF',
        strokeWidth: 2,
      },
      labels: {
        show: !props.minimalLabels,
        offsetY: -16,
        rounding: 1,
        color: '#1A1A1Aff',
        formatter: null,
      },
      area: {
        useGradient: true,
        opacity: 20,
      },
      tag: {
        followValue: true,
        formatter: null,
        fontSize: 14,
      },
    },
    plot: {
      showTransition: true,
      transitionDurationMs: 300,
      radius: 6,
      useGradient: true,
      dot: {
        useSerieColor: true,
        fill: '#FFFFFF',
        strokeWidth: 0.5,
      },
      labels: {
        show: true,
        offsetY: -8,
        rounding: 0,
        color: '#1A1A1Aff',
        formatter: null,
      },
      tag: {
        followValue: true,
        formatter: null,
        fontSize: 14,
      },
    },
    table: {
      useDialog: false,
      responsiveBreakpoint: 400,
      rounding: 0,
      sparkline: true,
      showSum: true,
      columnNames: {
        period: 'Period',
        total: 'Total',
      },
      th: {
        backgroundColor: '#FAFAFAff',
        color: '#1A1A1Aff',
        outline: '',
      },
      td: {
        backgroundColor: '#FAFAFAff',
        color: '#1A1A1Aff',
        outline: '',
      },
      useDefaultTimeFormat: true,
      timeFormat: 'yyyy-MM-dd HH:mm:ss',
    },
    showTable: false,
  }
})

const props = defineProps({
  dataset: {
    type: Object as PropType<VueUiXyDatasetItem[]>,
    default: () => {
      // Placeholder as default
      return <VueUiXyDatasetItem[]>[
        {
          name: 'Test',
          series: [1, 9, 7, 2, 12, 16, 17, 30, 16, 23],
          color: '#1f77b4',
          type: 'line',
          shape: 'hexagon',
          useArea: false,
          useProgression: true,
          dataLabels: true,
          smooth: true,
          dashed: false,
          useTag: 'none',
        },
        {
          name: 'name',
          series: [1, 4, 2, 4, 0],
          color: '#42d392',
          type: 'line',
          shape: 'circle',
          useArea: false,
          useProgression: false,
          dataLabels: true,
          smooth: true,
          dashed: false,
          useTag: 'none',
        },
      ]
    },
  },
  xAxisValues: {
    type: Object as PropType<string[]>,
    default: () => {
      return <string[]>[]
    },
  },
  yMin: {
    type: Number,
    default: 0,
  },
  minimalLabels: {
    type: Boolean,
    default: false,
  },
})
</script>
<template>
  <!-- Using a wrapper is optional -->
  <div :style="{ width: '100%' }">
    <VueUiXy :config="config" :dataset="props.dataset" />
  </div>
</template>
